### ISSUE TITLE
Module parse failed: Unexpected token (5:8)

### ISSUE THREAD

**Issue by 98ki** [MinaAndLuoXia/Taro-i18n#2]
./node_modules/taro-i18n/i18n.ts 5:8
Module parse failed: Unexpected token (5:8)
You may need an appropriate loader to handle this file type.
| export default class T {
| 
>   locale: string
|   locales
|   static t: T=new T('en',undefined)

**Comment by MinaAndLuoXia** [comment]
> ./node_modules/taro-i18n/i18n.ts 5：8
> 模块解析失败：意外的令牌（5：8）
> 您可能需要适当的加载程序来处理此文件类型。
> | 导出默认类T {
> |
> 
> > 语言环境：字符串
> > | 语言环境
> > | 静态t：T = new T（'en'，undefined）

源码改成js重新发布了,你可以通过npm install taro-i18n 更新,查看问题是否解决

**Comment by yimiIO** [comment]
解决了
